;  Generated by Latte compiler latc_x86
;  Source file: cls.asm
%include 'lib/runtime.ext'
section .rodata          ; "./cls.lat": 1,1
global _class_A          ; "./cls.lat": 1,7
_class_A:
DQ 0
DD 4
DQ _class_A_methods
DD 0
DQ 0
_class_A_methods:
global _class_Array
_class_Array:
DQ _class_Object
DD 16
DQ _class_Array_methods
DD 1
DQ _class_Array_refs
_class_Array_methods:
DQ _Object_equals
DQ _Object_getHashCode
DQ _Array_toString
_class_Array_refs:
DD 0
global _class_Object
_class_Object:
DQ 0
DD 0
DQ _class_Object_methods
DD 0
DQ 0
_class_Object_methods:
DQ _Object_equals
DQ _Object_getHashCode
DQ _Object_toString
global _class_String
_class_String:
DQ _class_Object
DD 0
DQ _class_String_methods
DD 0
DQ 0
_class_String_methods:
DQ _String_charAt
DQ _String_equals
DQ _String_concat
DQ _String_startsWith
DQ _String_endsWith
DQ _String_getBytes
DQ _String_indexOf
DQ _String_length
DQ _String_substring
DQ _String_toString
DQ _String_getHashCode
section .text            ; "./cls.lat": 1,1
global main              ; "./cls.lat": 5,1
main:                    ; "./cls.lat": 5,5
PUSH RBP                 ; "./cls.lat": 5,1
PUSH RBX
PUSH R12
PUSH R13
MOV RBP, RSP
SUB RSP, 8
PUSH R11
PUSH R10
MOV RDI, _class_A
MOV RBX, RSP
CALL __new
MOV RSP, RBX
MOV RBX, RAX
POP R10
POP R11
MOV R11, RBX
MOV R13, R11
TEST R13, R13
JZ $+12
MOV EBX, [R13 + 16]
INC EBX
MOV [R13 + 16], EBX
MOV R9, R11
MOV R13, R9
TEST R13, R13
JZ $+12
MOV EBX, [R13 + 16]
INC EBX
MOV [R13 + 16], EBX
SUB RSP, 8
PUSH R10
MOV RDI, R11
MOV RBX, RSP
CALL __decRef
MOV RSP, RBX
MOV RBX, RAX
POP R10
ADD RSP, 8
MOV RBX, RBX
MOV R12D, 32             ; "./cls.lat": 7,3
TEST R9, R9
JNZ $+7
CALL __errorNull
MOV R13, [R9 + 8]        ; "./cls.lat": 7,3
MOV [R13], R12D
SUB RSP, 8
PUSH R10
MOV RDI, R9
MOV RBX, RSP
CALL __decRef
MOV RSP, RBX
MOV RBX, RAX
POP R10
ADD RSP, 8
MOV RBX, RBX
TEST R9, R9
JNZ $+7
CALL __errorNull
MOV R12, [R9 + 8]        ; "./cls.lat": 8,12
MOV R11D, [R12]
SUB RSP, 8
PUSH R11
MOV RDI, R9
MOV RBX, RSP
CALL __decRef
MOV RSP, RBX
MOV RBX, RAX
POP R11
ADD RSP, 8
MOV RBX, RBX
MOV EDI, R11D
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
MOV RBX, RBX
MOV EAX, 0               ; "./cls.lat": 9,3
MOV RSP, RBP
POP R13
POP R12
POP RBX
POP RBP
RET