name:                instant-mrjp
version:             0.1.0.0
github:              "styczynski/instant-mrjp"
license:             MIT
author:              "Piotr Styczyński"
maintainer:          "piotr@styczynski.in"
copyright:           "2023 Piotr Styczyński (@styczynski)"

extra-source-files:
- LICENSE
- README.md

description: For details on usage please see README on GitHub at <https://github.com/styczynski/instant-mrjp#readme>

dependencies:
- filepath
- base >= 4.8 && < 5

library:
  source-dirs: src
  dependencies:
    - parser-combinators
    - mtl
    - megaparsec
    - containers
    - process
    - co-log
    - text
    - diagnose
    - jvm-parser
  default-extensions:
    - KindSignatures
    - LambdaCase
    - MultiWayIf
    - GADTs
    - DataKinds
    - RankNTypes
    - FlexibleContexts

executables:
  insc_jvm:
    main:                JVM.hs
    source-dirs:         cli/insc_jvm
    ghc-options:
      - -threaded
      - -O3
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - instant-mrjp
  insc_llvm:
    main:                LLVM.hs
    source-dirs:         cli/insc_llvm
    ghc-options:
      - -threaded
      - -O3
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - instant-mrjp
