name:                lattec
version:             0.1.0.0
github:              "styczynski/instant-mrjp"
license:             MIT
author:              "Piotr Styczyński"
maintainer:          "piotr@styczynski.in"
copyright:           "2023 Piotr Styczyński (@styczynski)"

extra-source-files:
- LICENSE
- README.md

description: For details on usage please see README on GitHub at <https://github.com/styczynski/instant-mrjp#readme>

dependencies:
- filepath
- base >= 4.8 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - process
    - co-log
    - text
    - diagnose
    - mtl
    - lens
    - array
    - transformers
    - keys
    - stacked-dag
    - fgl
    - fuzzyset
    - monad-extras
    - tuple-append
    - generic-lens
    - prettyprinter
    - prettyprinter-ansi-terminal
    - time
    - ordered-containers
    - deepseq
  default-extensions:
    - TypeSynonymInstances
    - KindSignatures
    - LambdaCase
    - MultiWayIf
    - TypeOperators
    - FunctionalDependencies
    - GADTs
    - TypeFamilies
    - StandaloneDeriving
    - DataKinds
    - OverloadedStrings
    - RankNTypes
    - FlexibleContexts

executables:
  latc_x86:
    main:                X86.hs
    source-dirs:         cli/lattec
    ghc-options:
      - -threaded
      - -O3
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lattec

