flags:
  diagnose:
    megaparsec-compat: true
allow-newer: true
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/17.yaml
packages:
- .
extra-deps:
  - co-log-0.6.0.2
  - diagnose-2.5.1
