;  Generated by Latte compiler latc_x86
;  Source file: test.asm
%include 'lib/runtime.ext'
section .rodata          ; "./test.lat": 1,1
global _class_Array
_class_Array:
DQ _class_Object
DD 16
DQ _class_Array_methods
DD 1
DQ _class_Array_refs
_class_Array_methods:
DQ _Object_equals
DQ _Object_getHashCode
DQ _Array_toString
_class_Array_refs:
DD 0
global _class_Object
_class_Object:
DQ 0
DD 0
DQ _class_Object_methods
DD 0
DQ 0
_class_Object_methods:
DQ _Object_equals
DQ _Object_getHashCode
DQ _Object_toString
global _class_String
_class_String:
DQ _class_Object
DD 0
DQ _class_String_methods
DD 0
DQ 0
_class_String_methods:
DQ _String_charAt
DQ _String_equals
DQ _String_concat
DQ _String_startsWith
DQ _String_endsWith
DQ _String_getBytes
DQ _String_indexOf
DQ _String_length
DQ _String_substring
DQ _String_toString
DQ _String_getHashCode
_S28:                    ; "./test.lat": 21,17
DB "foo"
DB 0
section .text            ; "./test.lat": 1,1
global main              ; "./test.lat": 1,1
main:                    ; "./test.lat": 1,5
PUSH RBP                 ; "./test.lat": 1,1
PUSH RBX
PUSH R13
MOV RBP, RSP
SUB RSP, 0
MOV EDI, 78              ; "./test.lat": 2,7
PUSH R10
PUSH R9
PUSH R8
PUSH RDX
PUSH RCX
PUSH RAX
PUSH RSI
PUSH RDI
MOV RBX, RSP
MOV RDI, 1
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
POP RDI
POP RSI
POP RAX
POP RCX
POP RDX
POP R8
POP R9
POP R10
MOV RBX, RBX
PUSH R10
PUSH R9
PUSH R8
PUSH RDX
PUSH RCX
PUSH RAX
PUSH RSI
PUSH RDI
MOV RBX, RSP
MOV RDI, 78
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
POP RDI
POP RSI
POP RAX
POP RCX
POP RDX
POP R8
POP R9
POP R10
MOV RBX, RBX
JMP _WCOND8              ; "./test.lat": 8,3
_WBEG9:
MOV EBX, EDI             ; "./test.lat": 9,5
SUB EBX, 1
MOV R11D, EBX
MOV EDI, R11D
PUSH R10
PUSH R9
PUSH R8
PUSH RDX
PUSH RCX
PUSH RAX
PUSH RSI
PUSH RDI
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
POP RDI
POP RSI
POP RAX
POP RCX
POP RDX
POP R8
POP R9
POP R10
MOV RBX, RBX
MOV EBX, EDI             ; "./test.lat": 13,14
ADD EBX, 7
MOV R11D, EBX
MOV ECX, R11D
PUSH R10
PUSH R9
PUSH R8
PUSH RDX
PUSH RCX
PUSH RAX
PUSH RSI
PUSH RDI
MOV RBX, RDI
MOV EDI, ECX
MOV RCX, RBX
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
POP RDI
POP RSI
POP RAX
POP RCX
POP RDX
POP R8
POP R9
POP R10
MOV RBX, RBX
_WCOND8:                 ; "./test.lat": 8,3
CMP EDI, 76              ; "./test.lat": 8,10
JG _WBEG9                ; "./test.lat": 8,12
PUSH R10
PUSH R9
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
POP R9
POP R10
MOV RBX, RBX
CMP EDI, 4               ; "./test.lat": 17,7
JLE _IELSE21             ; "./test.lat": 17,9
_IIF20:                  ; "./test.lat": 17,3
SUB RSP, 8
PUSH R10
MOV RDI, 4
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
POP R10
ADD RSP, 8
MOV RBX, RBX
JMP _IEND22              ; "./test.lat": 17,3
_IELSE21:
PUSH R11
PUSH R10
MOV RDI, _S28
MOV RBX, RSP
CALL __createString
MOV RSP, RBX
MOV RBX, RAX
POP R10
POP R11
MOV R11, RBX
MOV R13, R11
TEST R13, R13
JZ $+12
MOV EBX, [R13 + 16]
INC EBX
MOV [R13 + 16], EBX
PUSH R11
PUSH R10
MOV RDI, R11
MOV RBX, RSP
CALL printString
MOV RSP, RBX
MOV RBX, RAX
POP R10
POP R11
MOV RBX, RBX
SUB RSP, 8
PUSH R10
MOV RDI, R11
MOV RBX, RSP
CALL __decRef
MOV RSP, RBX
MOV RBX, RAX
POP R10
ADD RSP, 8
MOV RBX, RBX
_IEND22:                 ; "./test.lat": 17,3
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
MOV RBX, RBX
MOV EAX, 0               ; "./test.lat": 24,3
MOV RSP, RBP
POP R13
POP RBX
POP RBP
RET