;  Generated by Latte compiler latc_x86
;  Source file: core019.asm
%include 'lib/runtime.ext'
section .rodata          ; "./tests/good/core019.lat": 1,1
global _class_Array
_class_Array:
DQ _class_Object
DD 16
DQ _class_Array_methods
DD 1
DQ _class_Array_refs
_class_Array_methods:
DQ _Object_equals
DQ _Object_getHashCode
DQ _Array_toString
_class_Array_refs:
DD 0
global _class_Object
_class_Object:
DQ 0
DD 0
DQ _class_Object_methods
DD 0
DQ 0
_class_Object_methods:
DQ _Object_equals
DQ _Object_getHashCode
DQ _Object_toString
global _class_String
_class_String:
DQ _class_Object
DD 0
DQ _class_String_methods
DD 0
DQ 0
_class_String_methods:
DQ _String_charAt
DQ _String_equals
DQ _String_concat
DQ _String_startsWith
DQ _String_endsWith
DQ _String_getBytes
DQ _String_indexOf
DQ _String_length
DQ _String_substring
DQ _String_toString
DQ _String_getHashCode
_S10:                    ; "./tests/good/core019.lat": 21,17
DB "foo"
DB 0
section .text            ; "./tests/good/core019.lat": 1,1
global main              ; "./tests/good/core019.lat": 1,1
main:                    ; "./tests/good/core019.lat": 1,5
PUSH RBP                 ; "./tests/good/core019.lat": 1,1
PUSH RBX
PUSH R13
MOV RBP, RSP
SUB RSP, 0
MOV RDI, 1
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
MOV RBX, RBX
MOV RDI, 1
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
MOV RBX, RBX
MOV RDI, 1
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
MOV RBX, RBX
SUB RSP, 8
PUSH R11
MOV RDI, _S10
MOV RBX, RSP
CALL __createString
MOV RSP, RBX
MOV RBX, RAX
POP R11
ADD RSP, 8
MOV R11, RBX
MOV R13, R11
TEST R13, R13
JZ $+12
MOV EBX, [R13 + 16]
INC EBX
MOV [R13 + 16], EBX
SUB RSP, 8
PUSH R11
MOV RDI, R11
MOV RBX, RSP
CALL printString
MOV RSP, RBX
MOV RBX, RAX
POP R11
ADD RSP, 8
MOV RBX, RBX
MOV RDI, R11
MOV RBX, RSP
CALL __decRef
MOV RSP, RBX
MOV RBX, RAX
MOV RBX, RBX
MOV RDI, 1
MOV RBX, RSP
CALL printInt
MOV RSP, RBX
MOV RBX, RAX
MOV RBX, RBX
MOV EAX, 0               ; "./tests/good/core019.lat": 24,3
MOV RSP, RBP
POP R13
POP RBX
POP RBP
RET